### ISSUE TITLE
Cannot upload profile picture

### ISSUE THREAD

**Issue by Meuschke23** [dotsmesh/dotsmesh-web-app#4]
Hi,
if i upload a new profile picture for my public profile i get a error:

## Version:
![grafik](https://user-images.githubusercontent.com/65863113/97964045-69bb4280-1db8-11eb-95c9-c2ce7914c24c.png)

## Config:
```
<?php

return [
    'hosts' => ['meuschke.cloud'],
    'autoUpdate' => true,
    'updateSecret' => '*******************************'
];
```
## Error:
```
location:
https://dotsmesh.meuschke.cloud/#meuschke.meuschke.cloud

state:
{"type":"window","details":{"location":"user/home"}}

date:
Tue, 03 Nov 2020 08:40:42 GMT

user agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

name:
invalidResponse

message:
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

callAPI:
{"host":"meuschke.cloud","method":"user.dataStorage","response":""}
```

## Error (Log):
```
09:40:40:7337
Message:
Fatal error: Unknown: file created in the system's temporary directory in Unknown:0

Simple trace:

Full trace:
Array
(
)

Request:
POST https://dotsmesh.meuschke.cloud/

PHP variables:
Array
(
    [GET] => Array
        (
            [host] => 
            [api] => 
        )

    [POST] => Array
        (
        )

    [SERVER] => Array
        (
            [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            [PP_CUSTOM_PHP_INI] =>******/etc/php.ini
            [PP_CUSTOM_PHP_CGI_INDEX] => php74-fastcgi-nc
            [SCRIPT_NAME] => /index.php
            [REQUEST_URI] => /?host&api
            [QUERY_STRING] => host&api
            [REQUEST_METHOD] => POST
            [SERVER_PROTOCOL] => HTTP/1.0
            [GATEWAY_INTERFACE] => CGI/1.1
            [REMOTE_PORT] => 54886
            [SCRIPT_FILENAME] => ******/DotsMesh/index.php
            [SERVER_ADMIN] => [no address given]
            [CONTEXT_DOCUMENT_ROOT] => ******/meuschke.cloud/DotsMesh
            [CONTEXT_PREFIX] => 
            [REQUEST_SCHEME] => https
            [DOCUMENT_ROOT] => ******/DotsMesh
            [REMOTE_ADDR] => ******
            [SERVER_PORT] => 443
            [SERVER_ADDR] => ******
            [SERVER_NAME] => dotsmesh.meuschke.cloud
            [SERVER_SOFTWARE] => Apache
            [SERVER_SIGNATURE] => <address>Apache Server at dotsmesh.meuschke.cloud Port 443</address>

            [HTTP_COOKIE] => organizr_token_*********************
            [HTTP_ORIGIN] => https://dotsmesh.meuschke.cloud
            [CONTENT_TYPE] => application/json
            [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
            [HTTP_ACCEPT_LANGUAGE] => de,en-US;q=0.7,en;q=0.3
            [HTTP_ACCEPT] => application/json
            [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
            [CONTENT_LENGTH] => 149872
            [HTTP_CONNECTION] => close
            [HTTP_X_ACCEL_INTERNAL] => /internal-nginx-static-location
            [HTTP_X_REAL_IP] => ******
            [HTTP_HOST] => dotsmesh.meuschke.cloud
            [HTTPS] => on
            [PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY] => 0
            [PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY] => 0
            [FCGI_ROLE] => RESPONDER
            [PHP_SELF] => /index.php
            [REQUEST_TIME_FLOAT] => 1604392840.7179
            [REQUEST_TIME] => 1604392840
        )

)


```

Can you help me?

**Comment by ivopetkov** [comment]
Hi,
I believe there is something wrong with the directory where the source code and the data are stored. You can see the directory name in the /DotsMesh/index.php file (its only job is to include the app PHP file).

**Comment by Meuschke23** [comment]
Thank you for the fast reaction. As result i have reinstalled Dots Mesh with the Installscript:
Webserver Dir for dotsmesh.meuschke.cloud is: *****/httpdocs/meuschke.cloud/DotsMesh
![grafik](https://user-images.githubusercontent.com/65863113/98096283-db17f580-1e8b-11eb-8099-3db52f2ff71d.png)

there is a index.php:
```
<?php

require '***/httpdocs/meuschke.cloud/DotsMesh/Webapp/code/index.php';
```

and the Webapp folder
In the Webappfolder there is the config.php, the sourcecode and the data.
![grafik](https://user-images.githubusercontent.com/65863113/98096223-c20f4480-1e8b-11eb-8806-6308709d958a.png)


Is this wrong? Because i get the same errors. Now with the DotsMesh/Webapp Subdirectory.

It is an shared hosting environment powered by plesk.

**Comment by ivopetkov** [comment]
I found this description of the `upload_tmp_dir` php.ini option:
_The temporary directory used for storing files when doing file upload. Must be writable by whatever user PHP is running as. If not specified PHP will use the system's default._

I believe that the "file created in the system's temporary directory" error (it's actually a warning) is thrown because of switching to the system's default temp dir. I've never seen that before and I'll research more. It will be great if you research too and test different configurations.

**Comment by Meuschke23** [comment]
I think i got it.

In Plesk. i changed:
![grafik](https://user-images.githubusercontent.com/65863113/98159633-36be9f00-1edd-11eb-8e7a-dc2326e1b5c0.png)

to

![grafik](https://user-images.githubusercontent.com/65863113/98159655-4211ca80-1edd-11eb-88d6-f9e5c00ebace.png)

and now it seems to work. Thank you for the hint. This can be closed now.
